# -*- coding: utf-8 -*-
"""red-wine-quality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16TplkBeV4LCK8fI_gst2B9tMyf21bFbu

## **Về nhóm:**
Nhóm **Data Lord** gồm 4 thành viên:
- 19120625 - Nguyễn Hữu Phương 
- 18120278 - Phạm Hoàng Nam Anh
- 19120543 - Hoàng Mạnh Khiêm
- 19120522 - Phạm Quốc Hưng

# Bộ dữ liệu mô tả gì?

Bộ dữ liệu được thu thập trên trang Kaggle. <br>
Bộ dữ liệu này liên quan đến các đặc tính hóa lý của rượu vang "Vinho Verde" của Bồ Đào Nha. <br>
Bài toán: Xác định đặc tính hóa lý nào làm cho rượu trở nên 'ngon'?

# Input: 
- fixed acidity: hầu hết các axit liên quan đến rượu vang (cố định/không (dễ) bay hơi).           
- volatile acidity: lượng axit axetic trong rượu vang, ở mức quá cao có thể dẫn đến mùi giấm khó chịu.        
- citric acid: một lượng nhỏ axit xitric có thể thêm 'độ tươi' và hương vị cho rượu vang.             
- residual sugar: lượng đường còn lại sau khi ngừng lên men, hiếm khi tìm được loại rượu có hàm lượng dưới 1 gam/lít và loại rượu có hàm lượng lớn hơn 45 gam/lít được coi là ngọt.
- chlorides: lượng muối trong rượu vang.               
- free sulfur dioxide: dạng tự do của SO2 tồn tại ở trạng thái cân bằng giữa phân tử SO2 (ở dạng khí hòa tan) và ion bisulfit; nó ngăn chặn sự phát triển của vi sinh vật và quá trình oxy hóa của rượu vang.     
- total sulfur dioxide: số lượng các dạng tự do và ràng buộc của S02; ở nồng độ thấp SO2 hầu như không phát hiện được trong rượu, nhưng ở nồng độ SO2 tự do trên 50 ppm SO2 hiện rõ trong mùi và vị rượu.    
- density: độ đậm đặc của rượu so với nước, tùy thuộc vào phần trăm hàm lượng cồn và đường.               
- pH: mô tả mức độ axit hoặc cơ bản của rượu vang trên thang điểm từ 0-14 (càng nhỏ tính axit càng mạnh); hầu hết các loại rượu vang nằm trong khoảng từ 3-4 trên thang độ pH.                      
- sulphates: một chất phụ gia rượu vang có thể góp phần vào mức độ khí sulfur dioxide (S02), hoạt động như một chất chống vi trùng và chống oxy hóa.               
- alcohol: nồng độ cồn.    

# Out put: 
- quality: thang điểm cho rượu (0-10).

# Import
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!gdown https://drive.google.com/uc?id=1ljRP29kuVxvDetIAHbjK1RZsOyjqIbUi

data_df = pd.read_csv("winequality-red.csv")
data_df.head()

"""# Mô tả thống kê dữ liệu

Dữ liệu có bao nhiêu dòng/cột?
"""

num_rows = data_df.shape[0]
num_cols = data_df.shape[1]
print("Rows: ", num_rows)
print("Cols: ", num_cols)

"""Nhận xét: Dữ liệu có 1599 dòng và 12 cột.

Dữ liệu có các dòng bị lặp không?
"""

def check_duplicated(data):
    check = data.duplicated().sum()
    if check == 0:
        print("Dữ liệu không bị lặp!")
    else:
        print("Có " + str(check) + " dòng bị lặp!")

check_duplicated(data_df)
print("Thực hiện loại bỏ giá trị lặp")
data_df = data_df.drop_duplicates()
check_duplicated(data_df)

num_rows = data_df.shape[0]
num_cols = data_df.shape[1]
print("Rows: ", num_rows)
print("Cols: ", num_cols)

"""Các cột có kiểu dữ liệu gì và có bị thiếu hay không?"""

data_df.info()

"""Nhận xét: 
- Tất cả các cột input đều có kiểu dữ liệu float64 (kiểu số thực) và không bị thiếu dữ liệu.
- Cột dữ liệu output (quality) có kiểu dữ liệu int64 (kiểu số nguyên) và không bị thiếu dữ liệu.

# Mô tả thống kê cho dữ liệu Numerical
"""

round(data_df.describe(include=['float64', 'int64']), 2)

"""# Trực quan hóa dữ liệu

Phân bố của các cột dự liệu Numerical:
"""

numerical_data_df = pd.DataFrame(data_df)[pd.DataFrame(data_df).keys()].copy()
numerical_data_df

nrows = 4
ncols = 3
fig = plt.figure(figsize=(18, 15))
for i, col in enumerate(numerical_data_df):
    fig.add_subplot(nrows, ncols, i + 1)
    sns.boxplot(data= numerical_data_df, x= col, showmeans= True, color= 'orange')
plt.show()

nrows = 4
ncols = 3
fig = plt.figure(figsize=(18, 15))
for i, col in enumerate(numerical_data_df):
    fig.add_subplot(nrows, ncols, i + 1)
    sns.histplot(data=numerical_data_df, x=col, kde=True)
plt.show()

"""Nhận xét:
- Cột density và pH có phân phối chuẩn. Các cột còn lại phân phối lệch trái.
- Cột residual sugar có khoảng giá trị tập trung vào khoảng (1;3).
- Cột chlorides có khoảng giá trị tập trung vào khoảng (0;0.2).
- Cột total sulfur dioxide, sulphates có khoảng giá trị tập trung vào phần nhỏ hơn tứ phân vị thứ nhì Q2.
- Cột quality có các giá trị tập trung vào {5; 6}. Không có giá trị đạt max, min.

# Mối quan hệ giữa các cột dữ liệu Numerical
"""

plt.figure(figsize= (9, 8))
plt.title('Tương quan giữa các cột dữ liệu Numerical', fontsize=16)
sns.heatmap(data= numerical_data_df.corr(method= 'pearson'), cmap="YlGnBu", annot= True)
plt.show()

"""Nhận xét: 
- Hầu như tương quan giữa các cặp thuộc tính là tương quan yếu.
- Những cặp thuộc tính fixed acidity - citric axit - density và total sulfur dioxide - free sulfur dioxide có tương quan tương đối lớn hơn so với những thuộc tính còn lại.
"""

sns.pairplot(data= numerical_data_df)
plt.show()

"""Nhận xét:
- Các cặp thuộc tính đồng biến: fixed acidity - citric acid - density.
- Các cặp thuộc tính nghịch biến: pH - {fixed acidity - citric acid - density}
"""